-- 코드를 입력하세요
SELECT
       A.FOOD_TYPE
     , A.REST_ID
     , A.REST_NAME
     , A.FAVORITES
  FROM REST_INFO AS A
  JOIN (SELECT 
               B.FOOD_TYPE
             , MAX(B.FAVORITES) AS FAVORITES
          FROM REST_INFO AS B
         GROUP BY B.FOOD_TYPE) AS C ON (A.FOOD_TYPE = C.FOOD_TYPE AND C.FAVORITES = A.FAVORITES)
 ORDER BY A.FOOD_TYPE DESC;