-- 코드를 입력하세요
SELECT
       A.HISTORY_ID
     , A.CAR_ID
     , DATE_FORMAT(A.START_DATE, '%Y-%m-%d') AS START_DATE
     , DATE_FORMAT(A.END_DATE, '%Y-%m-%d') AS END_DATE
     , CASE
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) < 29 THEN '단기 대여'
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) >= 29 THEN '장기 대여'
       END AS 'RENT_TYPE'
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
 WHERE DATE_FORMAT(A.START_DATE, '%Y-%m') = '2022-09'
 ORDER BY A.HISTORY_ID DESC;