-- 코드를 입력하세요
SELECT
       A.WAREHOUSE_ID
     , A.WAREHOUSE_NAME
     , A.ADDRESS
     , IFNULL(A.FREEZER_YN, 'N')
  FROM FOOD_WAREHOUSE AS A
 WHERE A.WAREHOUSE_NAME LIKE '%경기%'
 ORDER BY A.WAREHOUSE_ID ASC;