-- 코드를 작성해주세요
SELECT 
       CONCAT(QUARTER(A.DIFFERENTIATION_DATE), 'Q') AS QUARTER
     , COUNT(QUARTER(A.DIFFERENTIATION_DATE)) AS ECOLI_COUNT
  FROM ECOLI_DATA AS A
 GROUP BY QUARTER
 ORDER BY QUARTER ASC;