-- 코드를 입력하세요
SELECT
       DATE_FORMAT(A.DATETIME, '%H') AS 'HOUR'
     , COUNT(DATE_FORMAT(A.DATETIME, '%H')) AS 'COUNT'
  FROM ANIMAL_OUTS AS A
 WHERE DATE_FORMAT(A.DATETIME, '%H') >= 9
   AND DATE_FORMAT(A.DATETIME, '%H') < 20
 GROUP BY DATE_FORMAT(A.DATETIME, '%H')
 ORDER BY DATE_FORMAT(A.DATETIME, '%H') ASC;